### ISSUE TITLE
problems with custom login credentials

### ISSUE THREAD

**Issue by deuspiritjk** [jhondmh/TDS-CRUD#2]
there is a problem with the use of custom credentials for login with social media like google.
i wanted to use my own credentials on .env but it does not work because the credentials was put directly on config/services.php.

```php
  'google' => [
        'client_id' => '791021486308-1rpi6ll11vrnp1j3j9h1odifbj4o9sdk.apps.googleusercontent.com',
        'client_secret' => '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',
        'redirect' => 'http://127.0.0.1:8000/auth/google/callback',
    ],
```

**Comment by jhondmh** [comment]
I already removed the credentials from the services.php file. Now it works correctly with your credentials?

**Comment by deuspiritjk** [comment]
yeah now it works :)
